feat: Drop in Attachments
twilio/twilio-conversations-demo-react pull request #136
Opened 2023-11-09 02:33 UTC by lesquive

**Description:**
This PR enables file drag-and-drop functionality within the Chat window. When a user drags a file over the designated drop zone, the component's background color dynamically changes to offer visual feedback. This functionality leverages the capabilities of the [react-dropzone](https://www.npmjs.com/package/react-dropzone) library.

accepted files:
```
    accept: {
      "image/*": [".png", ".jpeg", ".jpg", ".gif"],
    },
```

![Screen Recording 2023-11-08 at 20 14 01](https://github.com/twilio/twilio-conversations-demo-react/assets/51721338/3086a37d-81f9-4130-84f0-200924d38ef9)

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ x] I acknowledge that all my contributions will be made under the project's license.

2023-11-14 14:39 UTC, berkus commented
@lesquive hi, please resolve the conflicts!

2023-11-15 01:23 UTC, lesquive commented
@berkus merge conflicts fixed

2023-11-15 16:16 UTC, berkus requested changes

2023-11-15 16:16 UTC, berkus commented on src/components/conversations/ConversationContainer.tsx
> +  const handleDropedFiles = (droppedFiles: File[]) => {
drop**p**ed

2023-11-15 16:16 UTC, berkus commented on src/components/message/MessageList.tsx
> +    handleDropedFiles(files);
dropped...

2023-11-15 16:16 UTC, berkus commented on src/components/message/MessagesBox.tsx
> +  handleDropedFiles: (droppedFiles: File[]) => void;
dropped

2023-11-16 14:23 UTC, berkus approved these changes

2023-11-16 14:23 UTC, merged