feat(Messages): Added a new contextual menu with Edit and Delete options for Own Messages
twilio/twilio-conversations-demo-react pull request #151
Opened 2024-03-11 19:01 UTC by kmorope

Added a new contextual menu with Edit and Delete options for Own Messages

[RTDSDK-4281](https://issues.corp.twilio.com/browse/RTDSDK-4281)

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2024-04-04 09:32 UTC, berkus requested changes

2024-04-04 09:32 UTC, berkus commented on src/utils/emojiMapping.ts
> +export const emojiMapping: Record<Reactions, string> = {
that's probably better called "reactionsMapping"

2024-04-10 21:39 UTC, nicolas-camacho approved these changes

2025-04-28 11:56 UTC, AskAlice commented
🐌

2025-04-28 19:20 UTC, merged